server:
  port: 8083

spring:
  application:
    name: course-management
  datasource:
    url: jdbc:postgresql://localhost:5432/elemes?currentSchema=course_mgmt
    username: elemes
    password: elemes_local_dev
  flyway:
    enabled: true
    schemas: course_mgmt
    create-schemas: true
    default-schema: course_mgmt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/elemes

management:
  endpoints:
    web:
      exposure:
        include: health,info

opa:
  base-url: http://localhost:8181
